inherit_from: .rubocop_todo.yml

# rspec expect{...} is conventional
Layout/SpaceBeforeBlockBraces:
  Exclude:
    - 'spec/**/*_spec.rb'

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

# Configuration parameters: SupportedStyles.
Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

# Configuration parameters: AllowURI, URISchemes.
Layout/LineLength:
  Max: 177
