source "http://gemcutter.org"
source "http://gems.github.com"
source "http://sulair-rails-dev.stanford.edu"

gem "active-fedora", "~> 1.2.6"
gem "actionpack"
gem "activesupport"
gem 'activeresource'
gem "bagit", "~> 0.1.0"
gem "columnize"
gem "facets", "~> 2.9"
gem "fakeweb"
gem "gemcutter", "~> 0.6.1"
gem "git"
gem "haml"
gem "jeweler", "~> 1.4"
gem "json_pure", "~> 1.4.6"
gem "linecache", "~> 0.43"
gem "mime-types", "~> 1.16"
gem "multipart-post", "~> 1.0.1"
gem "nokogiri", "~> 1.4.3.1"
gem "rake", ">= 0.8.7"
gem "rcov"
gem "rdoc"
gem "roxml"
gem "rspec", "< 2.0"        # We're not ready to upgrade to rspec 2
gem "rubyforge"
gem "ruby-debug"
gem "semver", "~> 0.1.0"
gem "solr-ruby", "~> 0.0.8"
gem "solrizer", "~> 0.3.1"   # There was a bug in 0.3.0, we need at least the version after
gem "systemu", "~> 1.2.0"
gem "validatable"
gem "xml-simple", "~> 1.0.12"
gem "yard"